#!/usr/bin/env bash
# Based on http://openweathermap.org/current

API_KEY="e0160e7f77434e10242b1d7bab182e19"

# Check on http://openweathermap.org/find
CITY_ID="2638978" # Rugby, Warwickshire
#CITY_ID="1254649" # Thanjavur, India
FREEZING="#03D7FC"
COOL="#9E9E9E"
WARM="#F0C674"
HOT="#F5592F"

TEMP_NORMAL=0
TEMP_COOL=20
TEMP_WARM=30

SYMBOL_CELSIUS="℃"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

FEEL="$COOL"

if (( WEATHER_TEMP < TEMP_NORMAL )); then
  FEEL="$FREEZING"
elif (( WEATHER_TEMP >= TEMP_NORMAL && WEATHER_TEMP < TEMP_COOL )); then
  FEEL="$COOL"
elif (( WEATHER_TEMP >= TEMP_COOL && WEATHER_TEMP < TEMP_WARM )); then
  FEEL="$WARM"
elif (( WEATHER_TEMP >= TEMP_WARM )); then
  FEEL="$HOT"
fi

echo "%{F$FEEL}${WEATHER_TEMP}${SYMBOL_CELSIUS}%{F-}"
