swipe:
  3:
    left:
      command: "xdotool key super+Right"
    right:
      command: "xdotool key super+Left"
  4:
    left:
      command: "xdotool key super+ctrl+Right"
    right:
      command: "xdotool key super+ctrl+Left"
    up:
      command: "xdotool key super+minus"
    down:
      command: "xdotool key super+minus"

threshold:
  swipe: 0.5

interval:
  swipe: 0.75
