#!/usr/bin/env bash

if [[ -z "$1" ]]; then
  echo "Usage: brightness-hack [up|down]"
  exit 1
fi

TMPFILE=/tmp/brightness-hack

# http://www.geonames.org/
# Rugby cordinates - 52.37092:-1.26417

if [[ -f $TMPFILE ]]; then
  VAL=$(<$TMPFILE)
  if [[ "$1" == "up" ]]; then
    if [[ "$VAL" != "1.0" ]]; then
      NEWVAL=$(echo $VAL + 0.2 | bc)
      echo $NEWVAL > $TMPFILE
      redshift -m randr -x && redshift -m randr -o -l 52.37092:-1.26417 -t 5700:4000 -b $NEWVAL
    fi
  else
    if [[ "$VAL" != ".2" ]]; then
      NEWVAL=$(echo $VAL - 0.2 | bc)
      echo $NEWVAL > $TMPFILE
      redshift -m randr -x && redshift -m randr -o -l 52.37092:-1.26417 -t 5700:4000 -b $NEWVAL
    fi
  fi
else
  echo "1.0" > $TMPFILE
fi

