#!/usr/bin/env bash

[[ -z "$1" ]] && echo "nothing to do"
if [[ "$1" == "samsung" ]]; then
  xrandr --setprovideroutputsource 1 0
  xrandr --output DVI-I-1-1 --primary --mode 1920x1080 --output eDP-1 --off
elif [[ "$1" == "builtin" ]]; then
  xrandr --output eDP-1 --primary --mode 1920x1200 --output DVI-I-1-1 --off
fi

