#!/usr/bin/env bash

if [[ -z "$1" ]]; then
  echo "Usage: brightness-hack [up|down]"
  exit 1
fi

TMPFILE=/tmp/brightness-hack

if [[ -f $TMPFILE ]]; then
  VAL=$(<$TMPFILE)
  if [[ "$1" == "up" ]]; then
    if [[ "$VAL" != "1.0" ]]; then
      NEWVAL=$(echo $VAL + 0.2 | bc)
      echo $NEWVAL > $TMPFILE
      redshift -m randr -x && redshift -m randr -o -l 10.786999:79.137825 -t 5700:3000 -b $NEWVAL
    fi
  else
    if [[ "$VAL" != ".2" ]]; then
      NEWVAL=$(echo $VAL - 0.2 | bc)
      echo $NEWVAL > $TMPFILE
      redshift -m randr -x && redshift -m randr -o -l 10.786999:79.137825 -t 5700:3000 -b $NEWVAL
    fi
  fi
else
  echo "1.0" > $TMPFILE
fi

